# ===============================
# CONFIG IMPORT — charge .env.properties depuis la racine du projet
# Ce fichier contient les secrets et N'EST PAS commité dans Git
# ===============================
spring.config.import=optional:file:.env.prod.properties

# ===============================
# DATABASE
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# JWT
# ===============================
jwt.secret=${JWT_SECRET}
jwt.expiration=900000
jwt.refresh-expiration=604800000

# ===============================
# MAIL — Microsoft 365
# ===============================
spring.mail.host=smtp.office365.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# ===============================
# APP
# ===============================
app.base-url=${APP_BASE_URL}
app.upload-dir=uploads

# true  = affiche l'OTP dans les logs (développement)
# false = envoi réel via SMTP (production)
app.mail.console-mode=false

# ===============================
# FILE UPLOAD
# ===============================
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB

# ===============================
# LOGGING
# ===============================
logging.level.org.springframework.security=DEBUG
